### ISSUE TITLE
Suggestions for tasmin plots 

### ISSUE THREAD

**Issue by GLangendijk** [yaizaquintana/fps-urb-rcc#10]
@JavierDiezSierra @yaizaquintana, 

As indicated in my prior email, possibly the underneath suggestions could be incorporated in the respective figures? 

**Spatial TasMin Plot:** 
- Add  °C to the colourbar 
- Title: possibly revise into: "Minimum temperature anomaly for CITY" (we can explain in the figure caption that it is the anomaly with the respect to the surroundings?). 
- Could the city be mentioned in the Title - this would make it easier for interpretation. 
- Y-axis: change into: Minimum temperature anomaly (°C)

**Tasmin Anomaly plots:** 
- Rename "not urban mean" into "surroundings mean" or "vicinity mean"
- Title: possibly revise into: "Minimum temperature anomaly for CITY" 
- Could the city be mentioned in the Title - this would make it easier for interpretation. 
- Urban observations: change colour into black, for surroundings observations, possibly another colour? green? 
- Y-axis: change into: Minimum temperature anomaly (°C)

**Comment by jesusff** [comment]
moved to https://github.com/FPS-URB-RCC/CORDEX-CORE-WG/issues/12. Closing here
