### ISSUE TITLE
Selección de celdas no urbanas

### ISSUE THREAD

**Issue by JavierDiezSierra** [yaizaquintana/fps-urb-rcc#3]
@yaizaquintana 

Te pego debajo el algoritmo que vamos a usar para la selección de celdas no urbanas.

Por ahora vamos a usar un scale = 1 para -11 y un scale = 2 para -22.

La idea es que las celdas que no cumplan con el criterio de altitud y de agua se eliminen en cada iteración. Está comentado en el código.

Cualquier duda me comentas

```
import numpy as np
import xarray as xr
from skimage.morphology import dilation, square

# Create sample data
data = np.array([[0, 0, 0, 0, 0, 0],
                 [0, 0, 0, 0, 0, 0],
                 [0, 0, 1, 0, 0, 0],
                 [0, 1, 1, 1, 0, 0],
                 [0, 0, 0, 0, 0, 0],
                 [0, 0, 0, 0, 0, 0],
                 [0, 0, 0, 0, 0, 0],
                 [0, 0, 0, 0, 0, 0]])

# Convert data to xarray DataArray
data_array = xr.DataArray(data)

kernel = np.array([[0, 1, 0],
                   [1, 1, 1],
                   [0, 1, 0]])

scale = 4

urban_cells = np.sum(data)
non_urban_cells = 0
while non_urban_cells <= urban_cells * scale:
    # Perform dilation
    dilated_data = xr.apply_ufunc(dilation, 
                                  data_array if non_urban_cells == 0 else dilated_data, 
                                  kwargs={'footprint': kernel})
    #Delete other fixed variables (to include)
    #dilated_data[dilated_data == orography] = 0
    #dilated_data[dilated_data == landsea] = 0 
    
    non_urban_cells = np.sum(dilated_data) - urban_cells
dilated_data  = dilated_data - data
```

**Comment by yaizaquintana** [comment]
Te adjunto un jupyter con este algoritmo:
[select_non_urban.zip](https://github.com/yaizaquintana/Isla-Calor/files/15260612/select_non_urban.zip)

**Comment by yaizaquintana** [comment]
Versión corregida:
[select_non_urban.zip](https://github.com/yaizaquintana/Isla-Calor/files/15261526/select_non_urban.zip)

**Comment by JavierDiezSierra** [comment]
@yaizaquintana he generado un jupyter notebook con todo lo necesario para generar la función, o clase, para el tema de la selección de areas urbanas y no urbanas. La función se basa en lo que hiciste tú @yaizaquintana solo que he corregido algunas cosas que estaban mal en la selección del area no urbana y a la hora de aplicar las máscaras. Además he añadido algunos temas adiconales,  como por ejemplo un parámetro que define celdas que no son urbanas ni no urbanas, y algunas líneas para guardar los datos y las figuras.

El lunes lo vemos con @jesusff para decidir como hacer la función molona para poder publicarla.

@yaizaquintana añade por favor los últimos cambios que hiciste y habría que ver si la función se puede generalizar para 


[new_function_javi.zip](https://github.com/yaizaquintana/Isla-Calor/files/15285463/new_function_javi.zip)



![outputname-1](https://github.com/yaizaquintana/Isla-Calor/assets/32273213/353c8dde-3f91-49c5-aed6-03819efdc623)
