### ISSUE TITLE
 Cannot apply_along_axis when any iteration dimensions are 0, 

### ISSUE THREAD

**Issue by yaizaquintana** [yaizaquintana/fps-urb-rcc#7]
URBAN.define_masks:  Cannot apply_along_axis when any iteration dimensions are 0, 
error en linea: urban_elev_max = ds_orog.where(sftuf_mask).max().item()

error en:
CAM:REMO y RegCM
SAM-22 REMO y RegCM
WAS-22 RegCM
AUS--22: RegCM
AFR-22: RegCM

**Comment by JavierDiezSierra** [comment]
Resolved

**Comment by jesusff** [comment]
Please, always say where (in which commit?) it was resolved. @yaizaquintana, refer to lines using their permalink, so one can have a look easily
