### ISSUE TITLE
Cities across CORDEX domains

### ISSUE THREAD

**Issue by GLangendijk** [yaizaquintana/fps-urb-rcc#9]
Following the suggestion of Javier, to follow the IPCC sub-domain approach for mapping cities onto CORDEX domains (see here https://doi.org/10.1175/BAMS-D-22-0111.1), I have gathered the details for the 38 cities, as well as the additional cities for 0.11 res. - as we discussed. 

We could implement this into utils.py? 

@jesusff @JavierDiezSierra @yaizaquintana 

     'Jakarta': dict(lon = 106.83, lat = -6.18, domain = 'SEA-22'),
     'Manila': dict(lon = 120.98, lat = 14.60, domain = 'SEA-22'),
     'Mumbai [Bombay]': dict(lon = 72.82, lat = 18.96, domain = 'WAS-22'),
     'Dhaka': dict(lon = 90.41, lat = 23.70, domain = 'WAS-22'),
     'Delhi [New Delhi]': dict(lon = 77.22, lat = 28.64, domain = 'WAS-22'),
     'Tehran': dict(lon = 51.42, lat = 35.69, domain = 'WAS-22')
     'Cairo': dict(lon = 31.25, lat = 30.06, domain = 'AFR-22'),
     'New York' : dict(lon=-74.2261, lat=40.8858, domain = 'NAM-22'),
     'Tokyo' : dict(lon = 139.84, lat = 35.65, domain = 'EAS-22'),
     'Buenos Aires' : dict(lon=-58.416, lat=-34.559, domain = 'SAM-22'),
     'Sao Paulo' : dict(lon=-46.633, lat=-23.550, domain = 'SAM-22'),	
     'Los Angeles': dict(lon = -118.24, lat = 34.05, domain = 'NAM-22'),
     'Beijing' : dict(lon=116.41, lat=39.90, domain = 'EAS-22'),
     'Chengdu' : dict(lon=104.07, lat=30.67, domain = 'EAS-22'),
     'Mexico City' : dict(lon=-99.0833, lat=19.4667, domain = 'CAM-22'),
     'Johannesburg' : dict(lon=28.183, lat=-25.733, domain = 'AFR-22'),
     'Chicago': dict(lon = -87.55, lat = 41.73, domain = 'NAM-22'),
     'Montreal': dict(lon = -73.56, lat = 45.50, domain = 'NAM-22'),
     'Seoul': dict(lon = 126.98, lat = 37.57, domain = 'EAS-22'),
     'Lima': dict(lon = -77.03, lat = -12.04, domain = 'SAM-22'),
     'Lagos': dict(lon = 3.38, lat = 6.52, domain = 'AFR-22'),
     'Luanda': dict(lon = 13.24, lat = -8.81, domain = 'AFR-22'),
     'Riyadh' : dict(lon=46.73300, lat=24.7000, domain = 'WAS-22'),
     'Tashkent': dict(lon = 69.24, lat = 41.31, domain = 'WAS-22'),
     'Sydney' : dict(lon=151.01810, lat=-33.79170, domain = 'AUS-22'),
     'Shanghai': dict(lon = 121.47, lat = 31.23, domain = 'EAS-22'),
     'Baghdad': dict(lon = 44.40, lat = 33.34, domain = 'WAS-22'),
     'Khartoum': dict(lon = 32.53, lat = 15.58, domain = 'AFR-22'),
     'Santiago (Chile)': dict(lon = -70.65, lat = -33.46, domain = 'SAM-22'),
     'Melbourne': dict(lon = 144.96, lat = -37.81, domain = 'AUS-22'),
     'Singapore': dict(lon = 103.85, lat = 1.29, domain = 'SEA-22'),
     'Bogota': dict(lon = -74.06, lat = 4.62, domain = 'SAM-22'),

     ## European cities within Global Analysis (for REMO on 0.22 grid res as well)
     'Paris' : dict(lon=  2.35, lat=48.85, domain = 'EUR-11'),
     'London' : dict(lon= -0.13, lat=51.50, domain = 'EUR-11'),
     'Moscow' : dict(lon=37.62, lat=55.75, domain = 'EUR-11'),
     'Istanbul': dict(lon=28.98, lat=41.01, domain = 'EUR-11'),
     'Berlin' : dict(lon=13.4039, lat=52.4683, domain = 'EUR-11'),
     'Naples': dict(lon = 14.27, lat = 40.85, domain = 'EUR-11'),

     ## Additional cities for 0.11 - 0.22 comparison 
     'Barcelona': dict(lon = 2.18, lat = 41.39, domain = 'EUR-11'),
     'Athens': dict(lon = 23.72, lat = 37.98, domain = 'EUR-11'),
     'Prague': dict(lon = 14.42, lat = 50.08, domain = 'EUR-11'),

**Comment by jesusff** [comment]
moved to https://github.com/FPS-URB-RCC/CORDEX-CORE-WG/issues/13. Closing here
